# Generated by Django 3.1.7 on 2021-06-26 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/Galerie')),
            ],
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('produit', models.PositiveIntegerField()),
                ('datecreation', models.DateTimeField(auto_now=True, verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/produits')),
                ('fiche', models.FileField(blank=True, upload_to='fiche_technique')),
                ('libelle', models.CharField(max_length=30, unique=True)),
                ('Marque', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('Reference', models.CharField(max_length=20)),
                ('prix', models.FloatField()),
                ('poid', models.FloatField(blank=True, default=0)),
                ('dure', models.CharField(blank=True, max_length=20, null=True)),
                ('norme', models.CharField(blank=True, max_length=20, null=True)),
                ('datecreation', models.DateTimeField(auto_now=True, verbose_name='date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='publicite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/publicites')),
                ('status', models.CharField(default='en attente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='produitpromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseur.produit')),
            ],
        ),
    ]
