# Generated by Django 3.1.7 on 2021-06-26 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fournisseur', '0001_initial'),
        ('myAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produit',
            name='souscategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAdmin.souscategories'),
        ),
        migrations.AddField(
            model_name='galerie',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseur.produit'),
        ),
        migrations.AddField(
            model_name='caracteristique',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseur.produit'),
        ),
    ]
